# Form implementation generated from reading ui file 'frame.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(415, 463)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.bt_download = QtWidgets.QPushButton(parent=self.centralwidget)
        self.bt_download.setGeometry(QtCore.QRect(290, 348, 75, 24))
        self.bt_download.setObjectName("bt_download")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 208, 49, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 278, 49, 16))
        self.label_2.setObjectName("label_2")
        self.txt_link = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txt_link.setGeometry(QtCore.QRect(90, 208, 291, 22))
        self.txt_link.setObjectName("txt_link")
        self.txt_titulo = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txt_titulo.setGeometry(QtCore.QRect(90, 278, 291, 22))
        self.txt_titulo.setObjectName("txt_titulo")
        self.rb_mp3 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.rb_mp3.setGeometry(QtCore.QRect(50, 328, 61, 16))
        self.rb_mp3.setChecked(True)
        self.rb_mp3.setObjectName("rb_mp3")
        self.rb_mp4 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.rb_mp4.setGeometry(QtCore.QRect(50, 358, 61, 20))
        self.rb_mp4.setObjectName("rb_mp4")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(240, 30, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label.raise_()
        self.label_2.raise_()
        self.txt_link.raise_()
        self.txt_titulo.raise_()
        self.rb_mp3.raise_()
        self.rb_mp4.raise_()
        self.label_4.raise_()
        self.bt_download.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 415, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bt_download.setText(_translate("MainWindow", "download"))
        self.label.setText(_translate("MainWindow", "Link"))
        self.label_2.setText(_translate("MainWindow", "Título"))
        self.txt_link.setText(_translate("MainWindow", "https://www.youtube.com/watch?v=xCe9wnBjIcs"))
        self.rb_mp3.setText(_translate("MainWindow", "mp3"))
        self.rb_mp4.setText(_translate("MainWindow", "mp4"))
        self.label_4.setText(_translate("MainWindow", "Download"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
