# Form implementation generated from reading ui file 'sistema.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


#from PyQt6 import QtCore, QtGui, QtWidgets
#from PyQt6 import QTableWidgetItem
from PyQt6 import QtWidgets
from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMainWindow, QApplication, QTableWidget, QTableWidgetItem, QPushButton, QVBoxLayout, QWidget

import tkinter as tk
from tkinter.filedialog import askopenfilename 

import sys
from os.path import dirname, realpath, join
import pandas as pd
import numpy as np
from statsmodels.tsa.ar_model import AutoReg



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 629)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.bt_arquivo = QtWidgets.QPushButton(parent=self.centralwidget)
        self.bt_arquivo.setGeometry(QtCore.QRect(640, 60, 61, 31))
        self.bt_arquivo.setObjectName("bt_arquivo")
        self.rb_desvioPadrao = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.rb_desvioPadrao.setGeometry(QtCore.QRect(591, 219, 98, 20))
        self.rb_desvioPadrao.setObjectName("rb_desvioPadrao")
        self.rb_segregacao = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.rb_segregacao.setGeometry(QtCore.QRect(591, 333, 136, 20))
        self.rb_segregacao.setObjectName("rb_segregacao")
        self.rb_temporais = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.rb_temporais.setGeometry(QtCore.QRect(591, 447, 110, 20))
        self.rb_temporais.setObjectName("rb_temporais")
        self.rb_media = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.rb_media.setGeometry(QtCore.QRect(591, 162, 62, 20))
        self.rb_media.setChecked(True)
        self.rb_media.setObjectName("rb_media")
        self.rb_ponderada = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.rb_ponderada.setGeometry(QtCore.QRect(591, 276, 116, 20))
        self.rb_ponderada.setObjectName("rb_ponderada")
        self.rb_RegrecaoLinear = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.rb_RegrecaoLinear.setGeometry(QtCore.QRect(591, 390, 107, 20))
        self.rb_RegrecaoLinear.setObjectName("rb_RegrecaoLinear")
        self.bt_predizer = QtWidgets.QPushButton(parent=self.centralwidget)
        self.bt_predizer.setGeometry(QtCore.QRect(590, 500, 101, 51))
        self.bt_predizer.setObjectName("bt_predizer")
        self.txt_predicao = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txt_predicao.setGeometry(QtCore.QRect(30, 510, 551, 22))
        self.txt_predicao.setObjectName("txt_predicao")
        self.lb_PredicaoFaturamento = QtWidgets.QLabel(parent=self.centralwidget)
        self.lb_PredicaoFaturamento.setGeometry(QtCore.QRect(10, 50, 401, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.lb_PredicaoFaturamento.setFont(font)
        self.lb_PredicaoFaturamento.setObjectName("lb_PredicaoFaturamento")
        self.txt_totalfaturado = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txt_totalfaturado.setGeometry(QtCore.QRect(412, 60, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txt_totalfaturado.setFont(font)
        self.txt_totalfaturado.setText("")
        self.txt_totalfaturado.setObjectName("txt_totalfaturado")
        self.lb_totalFaturado = QtWidgets.QLabel(parent=self.centralwidget)
        self.lb_totalFaturado.setGeometry(QtCore.QRect(450, 30, 111, 16))
        self.lb_totalFaturado.setObjectName("lb_totalFaturado")
        self.sb_colunas = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.sb_colunas.setGeometry(QtCore.QRect(580, 70, 42, 22))
        self.sb_colunas.setObjectName("sb_colunas")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(590, 120, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.tb_faturamento = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tb_faturamento.setGeometry(QtCore.QRect(25, 111, 521, 381))
        self.tb_faturamento.setObjectName("tb_faturamento")
        self.tb_faturamento.setColumnCount(3)
        self.tb_faturamento.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tb_faturamento.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_faturamento.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_faturamento.setHorizontalHeaderItem(2, item)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bt_arquivo.setText(_translate("MainWindow", "Arquivo"))
        self.rb_desvioPadrao.setText(_translate("MainWindow", "Desvio Padrão"))
        self.rb_segregacao.setText(_translate("MainWindow", "Segregação de Dados"))
        self.rb_temporais.setText(_translate("MainWindow", "Series Temporais"))
        self.rb_media.setText(_translate("MainWindow", "  Média"))
        self.rb_ponderada.setText(_translate("MainWindow", "Média Ponderada"))
        self.rb_RegrecaoLinear.setText(_translate("MainWindow", "Regreção Linear"))
        self.bt_predizer.setText(_translate("MainWindow", "Predizer"))
        self.lb_PredicaoFaturamento.setText(_translate("MainWindow", "Predição de faturamento"))
        self.lb_totalFaturado.setText(_translate("MainWindow", "Total Faturado"))
        self.label_3.setText(_translate("MainWindow", "Tipo de predição"))
        item = self.tb_faturamento.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Ano"))
        item = self.tb_faturamento.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Mes"))
        item = self.tb_faturamento.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Faturamento"))

        self.bt_arquivo.clicked.connect(self.openFile)
        self.bt_predizer.clicked.connect(self.predicao)
    def openFile(self):
        
        #tk.Tk().withdraw()
        path = askopenfilename()
        self.all_data = pd.read_csv(path)

        # carrega o arquivo na tabela tb_faturamento
        numColumn = self.sb_colunas.value()
        if numColumn == 0:
           numRows = len(self.all_data.index) 
        else:
           numRows = numColumn  
        self.tb_faturamento.setColumnCount(len(self.all_data.columns)) 
        self.tb_faturamento.setRowCount(numRows) 
        self.tb_faturamento.setHorizontalHeaderLabels(self.all_data.columns)
        
        for i in range(numRows):
            for j in range(len(self.all_data.columns)):
                  self.tb_faturamento.setItem(i, j, QTableWidgetItem(str(self.all_data.iat[i,j])))
        self.tb_faturamento.resizeColumnsToContents()
        self.tb_faturamento.resizeRowsToContents
        # soma faturamento = str('R$%0)          
        soma_faturamento = str('R$%0.02f' %sum(self.all_data['Faturamento']))
        self.txt_totalfaturado.setText(soma_faturamento)

    def predicao(self):
        df = self.all_data
        ##media##
        if self.rb_media.isChecked():
            media = df["Faturamento"].mean()
            predicao = 'Nos próximos meses será faturado R$ '+ str('%0.02f' %media) + '/mes em media.'
            self.txt_predicao.setText(predicao)

        elif  self.rb_desvioPadrao.isChecked():
            media = df["Faturamento"].mean()
            devpad = df["Faturamento"].std()
            coe_var = (devpad / media)*100
            predicao = 'predição de R$ '+ str('%0.02f' %media) + '/mes podendo variar em torno de '+str('%0.02f' %coe_var)+'%'
            self.txt_predicao.setText(predicao)
        elif self.rb_ponderada.isChecked():
            lista = np.transpose((np.array([df['Faturamento'].tail(), np.arange(1,6)])))
            pesos = np.arange(1,6)
            df_ult = pd.DataFrame(lista, columns = ['Ultimos', 'Pesos'])
            df_ult['Ponderado'] = df_ult['Ultimos'] * df_ult['Pesos']
            med_pond = df_ult['Ponderado'].sum() / df_ult['Pesos'].sum()
            predicao = 'Predição ponderada de R$ ' + str('%0.02f' %med_pond) + ' para os próximos meses.'
            self.txt_predicao.setText(predicao) 
         ### Segregação dos Dados ###
        elif self.rb_segregacao.isChecked():
            df_janeiro = df.loc[df['Mes'] == 1]
            med_seg = df_janeiro['Faturamento'].mean()
            predicao = 'Predição segregada de R$ ' + str('%0.02f' %med_seg) + ' para janeiro.'
            self.txt_predicao.setText(predicao)
        ### Regressão Linear ###
        elif self.rb_RegrecaoLinear.isChecked():
            coefficients = np.polyfit(df.index, df['Faturamento'], 1)
            a = coefficients[0]
            b = coefficients[1]
            jan_reta = a * 36 + b
            predicao = 'Predição por regressão de R$ ' + str('%0.02f' %jan_reta) + ' para janeiro.'
            self.txt_predicao.setText(predicao)
        ### Series temporais ###
        elif self.rb_temporais.isChecked() == True:
            model = AutoReg(df['Faturamento'], lags=1, old_names=True) #old_names só foi utilizado por conta de um aviso da próxima versão
            model_fit = model.fit()
            yhat = model_fit.predict(len(df['Faturamento']), len(df['Faturamento'])+2)
            pred = np.array(yhat)
            predicao = 'Predição por serie temporal de R$ ' + str('%0.02f' %pred[0]) + ' para janeiro e R$ ' + str('%0.02f' %pred[1]) + ' para fevereiro.'
            self.txt_predicao.setText(predicao)    


if __name__ == "__main__":
    #import sys
    app = QtWidgets.QApplication(sys.argv)
    
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
