import pandas as pd

df = pd.DataFrame({'Empresa':[1,2,3,4],
                  'Vendedores':['Ana', 'Joao','Carlos','Bia'],
                  'Vendas':[120,60,365,120]})
#print(df)                  

print(df.head())
print()
print()
print('### Informações sobre dados únicos')
print()
print()
print(df['Vendas'].unique())

print('### Informações sobre dados únicos')
print()
print()
print(df['Vendas'].value_counts())


print()
print()
print('### Seleção de dados')
print()
print()
novodf = df[(df['Empresa'] > 2) & (df['Vendas'] > 120)]
print(novodf)

print()
print()
print('### Funções')
print()
print()

def multiplicacao(x):
    return x*2

print(df['Empresa'].apply(multiplicacao))
print()
print()
print('### Funções')
print()
print()
print(df['Vendas'].apply(multiplicacao))
print()
print()
print('### Funções')
print()
print()
print(df['Vendedores'].apply(len))
print()
print()
print('### Funções')
print()
print()
print(df['Vendas'].sum())
print()
print()
print('### Funções')
print()
print()

del df['Vendedores']
print(df)
print()
print()
print('### Funções numeros de colunas')
print()
print()
print(df.columns)
print()
print()
print('### Funções df.index')
print()
print()
print(df.index)
print()
print()
print('### Funções df.sort_values(by = "Vendas")')
print()
print()
print(df.sort_values(by = "Vendas"))
print()
print()
print('### Funções df.isnull()')
print()
print()
print(df.isnull())
print()
print()
print('### Funções df.dropna()')
print()
print()
print(df.dropna())
print()
print()
import numpy as np
df = pd.DataFrame({'Empresa':[1,2,np.nan,4],
                  'Vendedores':[np.nan, 'Joao','Carlos','Bia'],
                  'Vendas':[120,60,365,120]})
print('### NaN df.head()')
print()
print()
print(df.head())
print()
print()
print('### NaN df.fillna("Preenchido")')
print()
print()
print(df.fillna('Preenchido'))
print()
print()

print()
print()
print('### Pivot Table')
print()
print()
print()
print()
print()
dados = {'Empresas':['A','A','A','B','B','B'],
         'Vendedores':['Bia','Bia','Bia','João','João','João'],
         'Produtos':['salgados','doces','salgados','doces','salgados','doces'],
         'Vendas':[20,40,50,30,70,55]}
df = pd.DataFrame(dados)

print()
print()
print()
print()
print(df)
print()
print()
print('### Pivot Table')
print()
print()
print()
print()
print(df.pivot_table(values = 'Vendas', index = ['Empresas', 'Vendedores'], columns = 'Produtos'))

